### ISSUE TITLE
[Java] AtClientImpl refactoring to be similar to Dart SDK

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_java#33]
**Description**
The _get, _put, and _delete methods in `AtClientImpl.java` should follow similar Dart SDK methodologies.

**Tasks**
- [x] Implement key validation like in the Dart SDK (AtClientValidation)
- [x] Write AtClientValidation junit tests
- [x] Implement VerbBuilders (from, cram, pkam, llookup, lookup, plookup)
- [x] Write VerbBuilder junit tests
- [x] Assume SelfKey data is always encrypted (do not do `Metadata.isEncrypted` check)
- [x] Implement ResponseTransformers 
- [x] Use `llookup:all` to both 1. get the data and 2. update the Metadata in the AtKey object. (Use Transformers)

**Additional context**
Comment from gkc: https://github.com/atsign-foundation/at_java/pull/29#issuecomment-1197502834
Comment from VJag: https://github.com/atsign-foundation/at_java/pull/29#issuecomment-1197799153

**Comment by JeremyTubongbanua** [comment]
Tasks 3., 4., and 5., (VerbBuilders) : https://github.com/atsign-foundation/at_java/pull/36

**Comment by JeremyTubongbanua** [comment]
Tasks 1. and 2. (AtClientValidation) : #37

**Comment by JeremyTubongbanua** [comment]
Tasks 6 and 7 done on local machine, waiting on #40 (aka #36) to be merged
