### ISSUE TITLE
Tests AtClientImpl _put, _delete, and _get for PublicKey and SelfKey

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_java#47]
## tasks

- [ ] setup GitHub secrets with an atSign and the keys to that atSign
- [ ] make tests for _put, _get, and _delete PublicKey
- [ ] make tests for _put, _get, and _delete SelfKey
